import { useApp } from '../context/AppContext'
import { fmtGBP, fmt, calcPay } from '../utils'
import styles from './Payslip.module.css'

export default function Payslip() {
  const { currentUser, employees, getHoursForEmp } = useApp()
  const emp = employees.find(e => e.id === currentUser?.empId)

  if (!emp) return <p style={{ padding: 28, color: 'var(--text-muted)' }}>Employee record not found.</p>

  const month = '2025-07'
  const hours  = getHoursForEmp(emp.id, month)
  const { gross, tax, ni, net } = calcPay(hours, emp.rate)

  const Row = ({ label, value, highlight }) => (
    <div className={styles.row}>
      <span className={styles.rowLabel}>{label}</span>
      <span className={`${styles.rowValue} ${highlight ? styles[highlight] : ''}`}>{value}</span>
    </div>
  )

  return (
    <div className={styles.page}>
      <div className={styles.payslip}>
        {/* Header */}
        <div className={styles.header}>
          <div>
            <div className={styles.brandMark}>P</div>
            <h2 className={styles.brand}>PayrollPro</h2>
            <p className={styles.brandSub}>Monthly Payslip</p>
          </div>
          <div className={styles.headerRight}>
            <p className={styles.period}>July 2025</p>
            <p className={styles.issued}>Issued: 31 Jul 2025</p>
          </div>
        </div>

        {/* Employee details */}
        <div className={styles.section}>
          <p className={styles.sectionLabel}>Employee Details</p>
          <Row label="Name"         value={emp.name} />
          <Row label="Department"   value={emp.dept} />
          <Row label="Job Title"    value={emp.jobTitle} />
          <Row label="Hourly Rate"  value={`£${emp.rate}/hr`} />
        </div>

        {/* Earnings */}
        <div className={styles.section}>
          <p className={styles.sectionLabel}>Earnings</p>
          <Row label="Hours Worked" value={`${fmt(hours, 1)} hours`} />
          <Row label="Gross Pay"    value={fmtGBP(gross)} />
        </div>

        {/* Deductions */}
        <div className={styles.section}>
          <p className={styles.sectionLabel}>Deductions</p>
          <Row label="Income Tax (20%)"          value={`− ${fmtGBP(tax)}`} highlight="warning" />
          <Row label="National Insurance (12%)"  value={`− ${fmtGBP(ni)}`}  highlight="warning" />
        </div>

        {/* Net pay */}
        <div className={styles.total}>
          <span className={styles.totalLabel}>Net Pay</span>
          <span className={styles.totalValue}>{fmtGBP(net)}</span>
        </div>

        <p className={styles.footer}>
          This payslip is auto-generated by PayrollPro for demonstration purposes.
        </p>
      </div>
    </div>
  )
}
